version: '3'
################################################################
#                Networks                                      #
################################################################
networks:
  kbsbot-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

  # #############################################################
  # #                        Services                           #
  # #############################################################
services:
  compose-engine:
    restart: always
    image: astandre/kbsbot_compose_engine
    environment:
      - NLP_ENGINE_URL=http://172.28.1.4:5001
      - INTENTS_MANAGMENT_URL=http://172.28.1.3:5002
      - CONTEXT_MANAGMENT_URL=http://0.0.0.0:5003
    ports:
      - "5000:8000"
    networks:
      kbsbot-net:
        ipv4_address: 172.28.1.2

  nlp-engine:
    restart: always
    image: astandre/kbsbot_nlpengine
    ports:
      - "5001:8001"
    networks:
      kbsbot-net:
        ipv4_address: 172.28.1.3


  intents-managment:
    restart: always
    image: astandre/kbsbot_intents_managment
    ports:
      - "5002:8002"
    networks:
      kbsbot-net:
        ipv4_address: 172.28.1.4





